---
- hosts: all

  remote_user: vagrant
  sudo: True

  vars:
    sit_inst_dir: "/home/weblogic/sit_inst"
    sites_install_dir: "/home/weblogic/sit_inst/WebCenterSites_11.1.1.8.0/WCS_Sites/Sites/"

    weblogicuserhome: "/home/weblogic"
    oracle_repository: /home/angelo/vagrantVM/repo/Software/oracle

  tasks:

  - name: detect sites running (cs/cas)
    shell: " su - weblogic -c ' java weblogic.WLST ./appStatus.py' "
    register: check_sites
  - fail: STOP - CS and cas FAILED
    when: "'CS = STATE_FAILED' in check_sites.stdout and 'cas = STATE_FAILED' in check_sites.stdout"
  - fail: STOP - CS is up and running, cas doesnt
    when: "'CS = STATE_ACTIVE' in check_sites.stdout and 'cas = STATE_FAILED' in check_sites.stdout"
  - fail: STOP - cas is up and running, CS doesnt
    when: "'CS = STATE_FAILED' in check_sites.stdout and 'cas = STATE_ACTIVE' in check_sites.stdout"
  - fail: STOP - CS and cas are already up and running
    when: "'CS = STATE_ACTIVE' in check_sites.stdout and 'cas = STATE_ACTIVE' in check_sites.stdout"

  - name: set pre-install script
    copy: src=../files/master_install_pre.ini dest={{ sites_install_dir }}/install.ini
      owner=weblogic group=weblogic backup=yes

  - name: start deploy pre
    shell: " su - weblogic -c ' cd {{ sites_install_dir }} && echo | sh csInstall.sh -silent ' "
    register: site_install_pre
    ignore_errors: yes
    when: check_sites.stdout.find('STATE') != 0

  - name: stop weblogic
    service: name=weblogic state=stopped  pattern=weblogic.Server
    when: check_sites.stdout.find('STATE') != 0

  - name: check weblogic stop
    wait_for: port=7001 delay=1 timeout=60 state=stopped
    register: check_weblogic_stop

  - name: start weblogic
    service: name=weblogic state=started pattern=weblogic.Server
    when: check_sites.stdout.find('STATE') != 0

  - name: check weblogic start
    wait_for: port=7001 delay=1 timeout=120 state=started
    register: check_weblogic_start

  - name: start deploy multiple
    shell: " su - weblogic -c ' cd {{ sites_install_dir }} ; java weblogic.WLST ./deployMultiple.py ' "
    register: site_install_multiple
    ignore_errors: yes
    when: check_sites.stdout.find('STATE') != 0

  - name: set post-install script
    copy: src=../files/master_install_post.ini dest={{ sites_install_dir }}/install.ini
      owner=weblogic group=weblogic backup=yes

  - name: start deploy post
    shell: " su - weblogic -c ' cd {{ sites_install_dir }} ; echo | sh csInstall.sh -silent ' "
    register: site_install_post
    ignore_errors: yes
    when: check_sites.stdout.find('STATE') != 0

  - debug: var=site_install_post
    when: check_sites.stdout.find('STATE') != 0
