---
#- hosts: live:livemaster:satellite:apache
- hosts: all

  remote_user: vagrant
  sudo: True

  vars:
    oracle_repository: /opt/repo/oracle
    jdk_i586: jdk-linux-i586.rpm
    jdk_x64: jdk-linux-x64.rpm

  tasks:

  - name: download SUN jdk-7u55-linux-x64.rpm
    copy: src={{ oracle_repository }}/{{ jdk_x64 }} dest=/root
    when: ansible_machine == "x86_64"
  - name: download SUN jdk-7u55-linux-i586.rpm
    copy: src={{ oracle_repository }}/{{ jdk_i586 }} dest=/root
    when: ansible_machine == "i686"

  - name: need/install java 64bit
    shell: rpm -U --nosignature  /root/{{ jdk_x64 }}
    when: ansible_machine == "x86_64"
    register: rpm_install_result
    failed_when: not  "'is already installed' in rpm_install_result.stderr" 
  - name: need/install java 32bit
    shell: rpm -U --nosignature /root/{{ jdk_i586 }}
    when: ansible_machine == "i686"
    register: rpm_install_result
    failed_when: not  "'is already installed' in rpm_install_result.stderr" 

  - name: register java   append to alternatives
    shell: alternatives --install /usr/bin/java java /usr/java/latest/bin/java 20000
  - name: register java   select this java (sun)
    shell: alternatives --set  java /usr/java/latest/bin/java
  - name: setenv java via profile.d (add environment file)
    copy: src=../files/etc_profile.d_java.sh dest=/etc/profile.d/java.sh
      force=yes

  - name: run java to check version (just to be sure)
    shell: java -version
    # in case,  check stdout contents
    register: shell_result
    failed_when: not "'java version' in shell_result.stderr"

  - name: stop iptables
    service: name=iptables state=stopped
  - name: disable iptables
    action: command /sbin/chkconfig iptables off

  - name: install unzip
    yum: name=unzip state=present
